# Generated by Django 5.1.6 on 2025-04-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('description', models.CharField(max_length=1500, null=True)),
                ('reference', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouvelle_quantite', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleModifier', to='stock_products.article')),
            ],
        ),
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('reference', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('description', models.TextField(max_length=1000, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='stock_products.article')),
            ],
        ),
        migrations.CreateModel(
            name='ComposantModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouvelle_quantite', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composantModifier', to='stock_products.composant')),
            ],
        ),
    ]
