# Generated by Django 5.1.6 on 2025-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composant',
            name='article',
        ),
        migrations.AddField(
            model_name='composant',
            name='article',
            field=models.ManyToManyField(null=True, related_name='article', to='stock_products.article'),
        ),
    ]
