# Generated by Django 5.1.6 on 2025-05-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0002_remove_composant_article_composant_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composant',
            name='article',
            field=models.ManyToManyField(related_name='article', to='stock_products.article'),
        ),
    ]
