# Generated by Django 5.1.6 on 2025-05-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0003_alter_composant_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composant',
            name='article',
            field=models.ManyToManyField(blank=True, to='stock_products.article'),
        ),
    ]
