# Generated by Django 5.1.6 on 2025-05-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0004_alter_composant_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='composant',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
