# Generated by Django 5.1.6 on 2025-05-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0005_article_ordre_composant_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodifier',
            name='ancienne_quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlemodifier',
            name='mode',
            field=models.CharField(default='set', max_length=10),
        ),
        migrations.AddField(
            model_name='composantmodifier',
            name='ancienne_quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composantmodifier',
            name='mode',
            field=models.CharField(default='set', max_length=10),
        ),
    ]
