# Generated by Django 5.1.6 on 2025-05-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0006_articlemodifier_ancienne_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='objectif_journalier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='composant',
            name='objectif_journalier',
            field=models.IntegerField(default=0),
        ),
    ]
