# Generated by Django 5.1.6 on 2025-05-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0007_article_objectif_journalier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='objectif_journalier',
        ),
        migrations.RemoveField(
            model_name='composant',
            name='objectif_journalier',
        ),
    ]
