# Generated by Django 5.1.6 on 2025-02-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_rename_employe_utilisateur_alter_admin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
