# Generated by Django 5.1.6 on 2025-02-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_admin_user_alter_superadmin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
