# Generated by Django 5.1.6 on 2025-05-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_usertoken_delete_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
